# .github/workflows/go.yml
name: Go CI

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 系统作为运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码到运行环境

      - name: Set up Go
        uses: actions/setup-go@v4  # 设置 Go 环境
        with:
          go-version: '1.20'  # 指定 Go 的版本

      - name: Build
        run: go build -v ./...  # 编译项目

      - name: Set up Goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          distribution: goreleaser
          args: release --snapshot  # 修改 args 参数以包含 --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Hello World
        run: go run main.go  # 运行 Hello World 程序