# .github/workflows/go.yml
name: Go CI

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 系统作为运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码到运行环境

      - name: Set up Go
        uses: actions/setup-go@v4  # 设置 Go 环境
        with:
          go-version: '1.20'  # 指定 Go 的版本

      - name: Build
        run: go build -v ./...  # 编译项目

#      - name: Set up Goreleaser
#        uses: goreleaser/goreleaser-action@v4
#        with:
#          version: latest
#          tag_name: v0.1.0
#          distribution: goreleaser
#          args: release   # 移除 --snapshot 标志
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v0.1.0  # 使用推送的标签名
          release_name: "Release ${{ github.ref_name }}"
          body: "自动发布的 Release 版本"  # 可自定义或从文件读取
          draft: false  # 是否为草稿
          prerelease: false  # 是否为预发布
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 默认权限令牌

      - name: Run Hello World
        run: go run main.go  # 运行 Hello World 程序